#!/usr/bin/env bash

if [ "$APP_ENV" = "local" ]; then
    composer install --optimize-autoloader
    /usr/bin/supervisord

elif [ "$APP_ENV" = "production" ]; then
    composer install --no-ansi --no-dev --no-interaction --no-progress --no-suggest --optimize-autoloader
    /usr/bin/supervisord

else
    exec "$@"
fi
