version: '3'
services:
  app:
    build:
      context: docker/app
      dockerfile: Dockerfile
    image:
      laravelapp/app:latest
    networks:
      - appnet
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
      - 443:443
    working_dir: /var/www/html/
    depends_on:
      - mysql
      - redis
  node:
    build:
      context: docker/node
      dockerfile: Dockerfile
    image:
      laravelapp/node:latest
    networks:
      - appnet
    environment:
      - NODE_ENV=development
    volumes:
      - .:/opt/
    working_dir: /opt/
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - ${DB_PORT}:3306
    networks:
      - appnet
    volumes:
      - app-data:/var/lib/mysql
  redis:
    image: redis:5.0.7-alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - appnet
    volumes:
      - redis-data:/data
networks:
  appnet:
    driver: bridge
volumes:
  app-data:
    driver: local
  redis-data:
    driver: local
